export const API_PRODUCT_START = "API_PRODUCT_START";
export const API_PRODUCT_FILL = "API_PRODUCT_FILL";
export const API_PRODUCT_SUCCESS = "API_PRODUCT_SUCCESS";
export const API_PRODUCT_FAILED = "API_PRODUCT_FAILED";

export const API_PARCEL_START = "API_PARCEL_START";
export const API_PARCEL_SUCCESS = "API_PARCEL_SUCCESS";
export const API_PARCEL_FAILED = "API_PARCEL_FAILED";

export const PRODUCT_BY_ID_SUCCESS = "PRODUCT_BY_ID_SUCCESS";
export const PARCEL_BY_ID_SUCCES = "PARCEL_BY_ID_SUCCES";

export const API_USER_START = "API_USER_START";
export const API_USER_FAILED = "API_USER_FAILED";
export const API_USER_SUCCESS = "API_USER_SUCCESS";
export const API_CHECK_USER = "API_CHECK_USER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";
export const EDIT_TO_CART_SUCCESS = "EDIT_TO_CART_SUCCESS";

// Filter and sort
export const SORT_BY_ALPHABET = "SORT_BY_ALPHABET";
export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const LOAD_DATA = "LOAD_DATA";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";

export const NULLIFY_ERROR = "NULLIFY_ERROR";
